apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "argo-rollouts.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/istio-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: "{{ include "argo-rollouts.fullname" . }}-dashboard"
        port:
          number: {{ .Values.dashboard.service.port }}