apiVersion: v1
name: monitoring-stack
version: 1.0.0
appVersion: 1.0.0
description: monitoring stack includes node-exporter, kube-state-metrics, prometheus, prometheus-operator-crds and grafana to provide easy to operate cloud-native monitoring
keywords:
  - monitoring
dependencies:
  - name: prometheus
    version: 25.8.2
    repository: "file://./charts/prometheus"
  - name: metrics-server
    version: 3.11.0
    repository: "file://./charts/metrics-server"
  - name: grafana
    version: 7.2.1
    repository: "file://./charts/grafana"
