apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "keycloak.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  host: "{{ include "keycloak.fullname" . }}-http.{{ .Release.Namespace }}.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: SIMPLE
