apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "keycloak.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/istio-gateway
  http:
  - match:
    - uri: 
        prefix: /identity/connect/
    route:
    - destination:
        host: "{{ include "keycloak.fullname" . }}-http"
        port:
          number: {{ .Values.service.httpsPort }}
