apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: "{{ .Values.opensearch.fullnameOverride }}"
  namespace: {{ .Release.Namespace }}
spec:
  host: "{{ .Values.ingress.istio.host }}"
  trafficPolicy:
    tls:
      mode: DISABLE
