fluent-bit:
  image:
    repository: cr.fluentbit.io/fluent/fluent-bit
    # Overrides the image tag whose default is {{ .Chart.AppVersion }}
    # Set to "-" to not use the default value
    tag: 3.0.4
    pullPolicy: IfNotPresent

  fullnameOverride: "fluent-bit"

  resources: {}

  config:
    service: |
      [SERVICE]
          Daemon Off
          Flush {{ .Values.flush }}
          Log_Level {{ .Values.logLevel }}
          Parsers_File /fluent-bit/etc/parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port {{ .Values.metricsPort }}
          Health_Check On

    ## https://docs.fluentbit.io/manual/pipeline/inputs
    inputs: |
      [INPUT]
          Name tail
          Path /var/log/containers/fluent-bit*.log
          multiline.parser docker, cri
          Tag kube.*
          Mem_Buf_Limit 5MB
          Skip_Long_Lines On

      [INPUT]
          Name systemd
          Tag host.*
          Systemd_Filter _SYSTEMD_UNIT=kubelet.service
          Read_From_Tail On

    ## https://docs.fluentbit.io/manual/pipeline/filters
    filters: |
      [FILTER]
          Name kubernetes
          Match kube.*
          Merge_Log On
          Keep_Log Off
          K8S-Logging.Parser On
          K8S-Logging.Exclude On

    ## https://docs.fluentbit.io/manual/pipeline/outputs
    outputs: |
      [OUTPUT]
          Name opensearch
          Match kube.*
          Host opensearch-cluster-master
          Port 9200
          HTTP_User admin
          HTTP_Passwd admin
          tls On
          tls.verify Off
          Suppress_Type_Name On
          Logstash_Format On
          Logstash_Prefix fluentbit
          Replace_Dots On
          Generate_ID On
          Write_Operation upsert
          Trace_Error On

    ## https://docs.fluentbit.io/manual/pipeline/parsers
    customParsers: ""

    # This allows adding more files with arbitary filenames to /fluent-bit/etc/conf by providing key/value pairs.
    # The key becomes the filename, the value becomes the file content.
    extraFiles: {}

opensearch:
  singleNode: true

  # if not set, falls back to parsing .Values.imageTag, then .Chart.appVersion.
  majorVersion: "2.11.1"

  # such as opensearch.yml and log4j2.properties
  config:
    opensearch.yml: |
      cluster.name: opensearch-cluster
      compatibility.override_main_response_version: true

      # Bind to all interfaces because we don't know what IP address Docker will assign to us.
      network.host: 0.0.0.0

      # Setting network.host to a non-loopback address enables the annoying bootstrap checks. "Single-node" mode disables them again.
      # Implicitly done if ".singleNode" is set to "true".
      discovery.type: single-node

      # Start OpenSearch Security Demo Configuration
      # WARNING: revise all the lines below before you go into production
      plugins:
        security:
          ssl:
            transport:
              pemcert_filepath: esnode.pem
              pemkey_filepath: esnode-key.pem
              pemtrustedcas_filepath: root-ca.pem
              enforce_hostname_verification: false
            http:
              enabled: true
              pemcert_filepath: esnode.pem
              pemkey_filepath: esnode-key.pem
              pemtrustedcas_filepath: root-ca.pem
          allow_unsafe_democertificates: true
          allow_default_init_securityindex: true
          authcz:
            admin_dn:
              - CN=kirk,OU=client,O=client,L=test,C=de
          audit.type: internal_opensearch
          enable_snapshot_restore_privilege: true
          check_snapshot_restore_write_privileges: true
          restapi:
            roles_enabled: ["all_access", "security_rest_api_access"]
          system_indices:
            enabled: true
            indices:
              [
                ".opendistro-alerting-config",
                ".opendistro-alerting-alert*",
                ".opendistro-anomaly-results*",
                ".opendistro-anomaly-detector*",
                ".opendistro-anomaly-checkpoints",
                ".opendistro-anomaly-detection-state",
                ".opendistro-reports-*",
                ".opendistro-notifications-*",
                ".opendistro-notebooks",
                ".opendistro-asynchronous-search-response*",
              ]
      ######## End OpenSearch Security Demo Configuration ########

  image:
    repository: "opensearchproject/opensearch"
    # override image tag, which is .Chart.AppVersion by default
    tag: "2.11.1"

  opensearchJavaOpts: "-Xmx1G -Xms1G"

  resources:
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"

  persistence:
    storageClass: "nfs-retain-app"

  fullnameOverride: "opensearch"

opensearch-dashboards:
  opensearchHosts: "https://opensearch-cluster-master:9200"
  replicaCount: 1

  image:
    repository: "opensearchproject/opensearch-dashboards"
    # override image tag, which is .Chart.AppVersion by default
    tag: "2.11.1"

  fullnameOverride: "opensearch-dashboards"

  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "100m"
      memory: "512M"

  service:
    port: 5601

  config:
    # Default OpenSearch Dashboards configuration from docker image of Dashboards

    opensearch_dashboards.yml: |
      server.host: '0.0.0.0'
      server.basePath: "/opensearch"
      server.rewriteBasePath: true

      opensearch.hosts: ["https://opensearch-cluster-master:9200"]
      opensearch.ssl.verificationMode: none
      opensearch.username: admin
      opensearch.password: admin
      opensearch.requestHeadersWhitelist: [authorization, securitytenant]

      opensearch_security.multitenancy.enabled: true
      opensearch_security.multitenancy.tenants.preferred: [Private, Global]
      opensearch_security.readonly_mode.roles: [kibana_read_only]
      opensearch_security.cookie.secure: false

ingress:
  istio:
    host: "opensearch-dashboards"
    port: 5601