server:
  fullnameOverride: prometheus-server
  image: 
    repository: quay.io/prometheus/prometheus
    tag: v2.48.1

  global:
    ## How frequently to scrape targets by default
    scrape_interval: 10s
  persistentVolume:
    ## Prometheus server data Persistent Volume size
    size: 8Gi
  resources: {}
    # limits:
    #   cpu: 500m
    #   memory: 512Mi
    # requests:
    #   cpu: 500m
    #   memory: 512Mi
  
  ## Prometheus data retention period (default if not specified is 15 days)
  retention: "7d"
## alertmanager sub-chart configurable values
alertmanager:
  ## If false, alertmanager will not be installed
  enabled: false
## kube-state-metrics sub-chart configurable values
kube-state-metrics:
  ## If false, kube-state-metrics sub-chart will not be installed
  enabled: true
  image:
    registry: registry.k8s.io
    repository: kube-state-metrics/kube-state-metrics
    tag: v2.10.1
  fullnameOverride: kube-state-metrics
## prometheus-node-exporter sub-chart configurable values
prometheus-node-exporter:
  ## If false, node-exporter will not be installed
  enabled: false
  image:
    registry: quay.io
    repository: prometheus/node-exporter
    tag: v1.7.0
  fullnameOverride: node-exporter
## prometheus-pushgateway sub-chart configurable values
prometheus-pushgateway:
  ## If false, pushgateway will not be installed
  enabled: false