apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "argo-cd.server.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/istio-gateway
  http:
  - match:
    - uri:
        prefix: /argocd
    route:
    - destination:
        host: "{{ template "argo-cd.server.fullname" . }}"
        port:
          number: {{ .Values.server.service.servicePortHttp }}